service: add-to-notion-db
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable/index/*"
        - Effect: Allow # allow s3 write
          Action:
            - s3:PutObject
          Resource: "arn:aws:s3:::*/*"
  environment:
    NOTION_TOKEN: ${file(./config.yaml):NOTION_TOKEN}
    ITEMS_DATABASE_ID: ${file(./config.yaml):ITEMS_DATABASE_ID}
    TAG_DATABASE_ID: ${file(./config.yaml):TAG_DATABASE_ID}
    S3_BUCKET: ${file(./config.yaml):S3_BUCKET}

functions:
  main:
    handler: src/webhook.onHttpRequest
    events:
      - http:
          path: /
          method: post
          cors: false
          private: false
  alexaSkill:
    handler: src/alexa.onAlexaInvocation
    events:
      - alexaSkill:
          appId: ${file(./config.yaml):ALEXA_SKILL_ID}
          enabled: true
  telegramBot:
    handler: src/telegram.handler
    events:
      - http:
          path: telegram
          method: post
          cors: false
          private: false

plugins:
  - serverless-esbuild

resources:
  Resources:
    tagTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tagTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    s3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(./config.yaml):S3_BUCKET}
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              AllowedOrigins:
                - '*'
              MaxAge: 0