service: add-to-notion-db
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable/index/*"

functions:
  main:
    handler: handler.main
    environment:
      NOTION_TOKEN: ${file(./config.yaml):NOTION_TOKEN}
      ITEMS_DATABASE_ID: ${file(./config.yaml):ITEMS_DATABASE_ID}
      TAG_DATABASE_ID: ${file(./config.yaml):TAG_DATABASE_ID}
    events:
      - http:
          path: /
          method: post
          cors: false
          private: false

plugins:
  - serverless-esbuild
  - serverless-dynamodb-local

resources:
  Resources:
    tagTable:
      # TODO: add ttl
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tagTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true