service: add-to-notion-db
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/tagTable/index/*"
  environment:
    NOTION_TOKEN: ${file(./config.yaml):NOTION_TOKEN}
    ITEMS_DATABASE_ID: ${file(./config.yaml):ITEMS_DATABASE_ID}
    TAG_DATABASE_ID: ${file(./config.yaml):TAG_DATABASE_ID}

functions:
  main:
    handler: src/webhook.onHttpRequest
    events:
      - http:
          path: /
          method: post
          cors: false
          private: false
  alexaSkill:
    handler: src/alexa.onAlexaInvocation
    events:
      - alexaSkill:
          appId: ${file(./config.yaml):ALEXA_SKILL_ID}
          enabled: true

plugins:
  - serverless-esbuild

resources:
  Resources:
    tagTable:
      # TODO: add ttl
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tagTable
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
